
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftORleftANDnonassocLEGELTGTEQNErightELSEnonassocIFAND ELSE EQ GE GT IDENT IF LBRACE LE LPAREN LT NE NUMBER ON_INTENT OR RBRACE REPLY RPAREN SCENE SEMI STRINGscript : scene_stmt intent_stmt if_blocksscene_stmt : SCENE IDENTintent_stmt : ON_INTENT IDENTif_blocks : if_block\n| if_block else_block\n| if_blocks else_if_block\n| if_blocks else_blockelse_if_blocks : else_if_block\n| else_if_blocks else_if_blockif_block : IF expr REPLY STRINGelse_if_block : ELSE IF expr REPLY STRINGelse_block : ELSE REPLY STRINGexpr : expr logical_op exprexpr : LPAREN expr RPARENexpr : atomatom : IDENT compare_op valueatom : IDENTvalue : NUMBER\n| STRINGlogical_op : AND \n| ORcompare_op : LE \n| GE \n| LT \n| GT \n| EQ \n| NE'
    
_lr_action_items = {'SCENE':([0,],[3,]),'$end':([1,7,8,11,12,14,35,36,43,],[0,-1,-4,-6,-7,-5,-12,-10,-11,]),'ON_INTENT':([2,6,],[5,-2,]),'IDENT':([3,5,9,17,20,23,24,25,],[6,10,19,19,19,19,-20,-21,]),'IF':([4,10,13,],[9,-3,20,]),'ELSE':([7,8,11,12,14,35,36,43,],[13,15,-6,-7,-5,-12,-10,-11,]),'LPAREN':([9,17,20,23,24,25,],[17,17,17,17,-20,-21,]),'REPLY':([13,15,16,18,19,34,37,38,39,40,41,],[21,21,22,-15,-17,42,-13,-14,-16,-18,-19,]),'AND':([16,18,19,26,34,37,38,39,40,41,],[24,-15,-17,24,24,24,-14,-16,-18,-19,]),'OR':([16,18,19,26,34,37,38,39,40,41,],[25,-15,-17,25,25,25,-14,-16,-18,-19,]),'RPAREN':([18,19,26,37,38,39,40,41,],[-15,-17,38,-13,-14,-16,-18,-19,]),'LE':([19,],[28,]),'GE':([19,],[29,]),'LT':([19,],[30,]),'GT':([19,],[31,]),'EQ':([19,],[32,]),'NE':([19,],[33,]),'STRING':([21,22,27,28,29,30,31,32,33,42,],[35,36,41,-22,-23,-24,-25,-26,-27,43,]),'NUMBER':([27,28,29,30,31,32,33,],[40,-22,-23,-24,-25,-26,-27,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'script':([0,],[1,]),'scene_stmt':([0,],[2,]),'intent_stmt':([2,],[4,]),'if_blocks':([4,],[7,]),'if_block':([4,],[8,]),'else_if_block':([7,],[11,]),'else_block':([7,8,],[12,14,]),'expr':([9,17,20,23,],[16,26,34,37,]),'atom':([9,17,20,23,],[18,18,18,18,]),'logical_op':([16,26,34,37,],[23,23,23,23,]),'compare_op':([19,],[27,]),'value':([27,],[39,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> script","S'",1,None,None,None),
  ('script -> scene_stmt intent_stmt if_blocks','script',3,'p_script','parser.py',19),
  ('scene_stmt -> SCENE IDENT','scene_stmt',2,'p_scene_stmt','parser.py',23),
  ('intent_stmt -> ON_INTENT IDENT','intent_stmt',2,'p_intent_stmt','parser.py',28),
  ('if_blocks -> if_block','if_blocks',1,'p_if_blocks','parser.py',35),
  ('if_blocks -> if_block else_block','if_blocks',2,'p_if_blocks','parser.py',36),
  ('if_blocks -> if_blocks else_if_block','if_blocks',2,'p_if_blocks','parser.py',37),
  ('if_blocks -> if_blocks else_block','if_blocks',2,'p_if_blocks','parser.py',38),
  ('else_if_blocks -> else_if_block','else_if_blocks',1,'p_else_if_blocks','parser.py',43),
  ('else_if_blocks -> else_if_blocks else_if_block','else_if_blocks',2,'p_else_if_blocks','parser.py',44),
  ('if_block -> IF expr REPLY STRING','if_block',4,'p_if_block','parser.py',48),
  ('else_if_block -> ELSE IF expr REPLY STRING','else_if_block',5,'p_else_if_block','parser.py',54),
  ('else_block -> ELSE REPLY STRING','else_block',3,'p_else_block','parser.py',60),
  ('expr -> expr logical_op expr','expr',3,'p_expr_bin','parser.py',66),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_expr_group','parser.py',73),
  ('expr -> atom','expr',1,'p_expr_atom','parser.py',77),
  ('atom -> IDENT compare_op value','atom',3,'p_atom_compare','parser.py',81),
  ('atom -> IDENT','atom',1,'p_atom_exists','parser.py',98),
  ('value -> NUMBER','value',1,'p_value','parser.py',104),
  ('value -> STRING','value',1,'p_value','parser.py',105),
  ('logical_op -> AND','logical_op',1,'p_logical_op','parser.py',109),
  ('logical_op -> OR','logical_op',1,'p_logical_op','parser.py',110),
  ('compare_op -> LE','compare_op',1,'p_compare_op','parser.py',114),
  ('compare_op -> GE','compare_op',1,'p_compare_op','parser.py',115),
  ('compare_op -> LT','compare_op',1,'p_compare_op','parser.py',116),
  ('compare_op -> GT','compare_op',1,'p_compare_op','parser.py',117),
  ('compare_op -> EQ','compare_op',1,'p_compare_op','parser.py',118),
  ('compare_op -> NE','compare_op',1,'p_compare_op','parser.py',119),
]
